/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@app$': '<rootDir>/src/app',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@helpers/(.*)$': '<rootDir>/src/helpers/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@types-internal/(.*)$': '<rootDir>/src/types/$1',
    '^@interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@events/(.*)$': '<rootDir>/src/events/$1',
    '^@jobs/(.*)$': '<rootDir>/src/jobs/$1',
    '^@queues/(.*)$': '<rootDir>/src/queues/$1',
    '^@emails/(.*)$': '<rootDir>/src/emails/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@database/(.*)$': '<rootDir>/src/database/$1',
  },
  setupFiles: ['<rootDir>/tests/setup-env.ts'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup-after-env.ts'],
  testTimeout: 30000,
  collectCoverageFrom: ['src/**/*.ts', '!src/**/*.d.ts', '!src/server.ts', '!src/database/seeds/**'],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['/node_modules/', '/dist/'],
  verbose: true,
  forceExit: true,
  clearMocks: true,
};
